### ISSUE TITLE
您好，NodePort的端口可以指定吗？

### ISSUE THREAD

**Issue by noahge** [resf/istio#150]
现在装完的istio，nodeport的端口是随机的，我是mac系统，用kind做的kubernetes的集群，docker没有网桥，不能直接和集群通信，只能通过kind的配置文件，映射nodeport来和集群通信，每次修改kind集群的nodeport配置，都需要把集群删除再重新创建才行，但是重新创建后，istio一重装，端口又不一样了，导致现在没法正常使用istio，请问有什么办法解决吗？感谢！

**Comment by morlay** [comment]
@noahge 这个项目只管编译，用法去官网看
